### ISSUE TITLE
Allow filtering prompts by any field in the UI

### ISSUE THREAD

**Issue by aquirin-te** [comet-ml/opik#116]
It would be useful to search/filter LLM prompts using any field: metadata (key and content), tags, model name, model type, date, user feedbacks, etc.

Unfortunately the search fields are a bit limited for the moment:

<img width="210" alt="image" src="https://github.com/comet-ml/comet-llm/assets/98026510/c1becf34-9f9e-4478-bc6f-7a773a7bce91">

Note that it is possible to filter using the Comet Experiment API by code, but adding the capability to the UI would be quite useful indeed.

**Comment by Nimrod007** [comment]
Hi @aquirin-te, we are moving to a new product opik https://github.com/comet-ml/opik/ which will replace comet-llm.

You can find the old comet-llm project here: https://github.com/comet-ml/comet-llm-legacy
