### ISSUE TITLE
Any way to user commet_llm as object?

### ISSUE THREAD

**Issue by DmitriiShubin** [comet-ml/opik#137]
example:
a = comet_llm.init()
a.start_chain(...)

My agent has multiple files and complex module structure, super inconvenient to use rn as a global variable

**Comment by Lothiraldan** [comment]
Hi @DmitriiShubin, thank you for raising your pain point. The usage of a global variable is meant to making it easier for you to use our LLM SDK and not requiring your to update all functions in your call stack to pass the LLM SDKs around.
Could you share a bit more information about your use-case and agent setup? Does your agent runs across multiple threads, coroutines or processes?

**Comment by DmitriiShubin** [comment]
Hi Boris,

We need to track the performance of the multi-agent system, ideally
end2end, which consists of multiple classes and dozens of API calls.

Also, how are you guys compliant with the security? do you use/review
logs/prompts?

**Comment by DmitriiShubin** [comment]
> Does your agent runs across multiple threads, coroutines or processes?
Rn it isn't but we're planning to add multi-threading in a near future

**Comment by Lothiraldan** [comment]
> Also, how are you guys compliant with the security? do you use/review logs/prompts?

Our terms of service https://www.comet.com/site/terms-of-service/ and Privacy Policy https://www.comet.com/site/privacy-policy/ cover this.  In general user owns their data stored in comet unless they set it to public. In addition for security we are SOC2 and ISO 27001 complaint.

>  Rn it isn't but we're planning to add multi-threading in a near future

Sounds good, would you be willing to jump on a call to explore what the best API would be for your use-case?

**Comment by DmitriiShubin** [comment]
sure, please feel free to reach out shubin.dmitrii@gmail.com

**Comment by DmitriiShubin** [comment]
and thanks for the info!

**Comment by Nimrod007** [comment]
Hi @DmitriiShubin , we are moving to a new product opik https://github.com/comet-ml/opik/ which will replace comet-llm.

You can find the old comet-llm project here: https://github.com/comet-ml/comet-llm-legacy
