### ISSUE TITLE
Please add an option to name a chain

### ISSUE THREAD

**Issue by tttalshaul** [comet-ml/opik#141]
in comet_llm.start_chain() it would be useful to allow adding parameter "name" = "XXX" and then created chains will be named XXX-0 XXX-1 or XXX-random numbers/chars. 
It would be especially useful in multi-agent scenarios..

**Comment by Nimrod007** [comment]
Hi @tttalshaul, we are moving to a new product `opik` https://github.com/comet-ml/opik/ which will replace `comet-llm`.

You can find the old comet-llm project here: https://github.com/comet-ml/comet-llm-legacy
