### ISSUE TITLE
[FR]: Include REST API in documentation

### ISSUE THREAD

**Issue by Kylescottw** [comet-ml/opik#319]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

It would be helpful if the REST API endpoints were documented.
That way users can easily use languages that do not yet have an Opik SDK. 

### Motivation

**What problem are you trying to solve?** 
Enable using Opik with node.js

**How are you currently solving this problem?** 
Deduce the api calls within the python sdk

**What are the benefits of this feature?**
Allow easier access for developers using other languages than python

**Comment by jverre** [comment]
Hi @Kylescottw 

I have added the Rest API docs to the documentation: [https://www.comet.com/docs/opik/reference/rest_api/opik-rest-api](https://www.comet.com/docs/opik/reference/rest_api/opik-rest-api)

The REST API is in beta meaning it might be subject to change but so far everything has been pretty stable
