### ISSUE TITLE
[FR]: LiteLLM integration

### ISSUE THREAD

**Issue by antonkulaga** [comet-ml/opik#328]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

Add Litellm integration

### Motivation

[https://www.litellm.ai/](Litellm) (including Litellm proxy) is a leightweight wrapper that makes models openai compartible. opik will benefit a lot if it will add its integration

**Comment by sherpan** [comment]
Hi @antonkulaga ! we have an [open PR ](https://github.com/BerriAI/litellm/pull/5680)with litellm for an Opik Integration! Would appreciate any comments/upvotes on the PR to get it merged soon!

**Comment by antonkulaga** [comment]
Thank you @sherpan ! I see your PR was merged, so now looking forward for litellm specific opik setup instruction to test it in our projects

**Comment by veer-debug** [comment]
can anyone elaborate the issue

**Comment by jverre** [comment]
@antonkulaga @veer-debug The PR was indeed merged but the integration was not implemented. Based on feedback from the LiteLLM team, we re-implemented the integration in this PR: https://github.com/BerriAI/litellm/pull/6062

We are currently waiting for the LiteLLM team to get back to us as we ran into an issue with the recommended approach, we are hoping to hear back and have the integration merged in soon !

**Comment by jverre** [comment]
@veer-debug @antonkulaga The integration was merged and the documentation was updated: https://www.comet.com/docs/opik/tracing/integrations/litellm

If you have any questions, let me know
