### ISSUE TITLE
[Bug]: Cannot pass project_name to track decorator when using opik.evaluation.evaluate

### ISSUE THREAD

**Issue by anmorgan24** [comet-ml/opik#420]
### Willingness to contribute

No. I can't contribute a fix for this bug at this time.

### What component(s) are affected?

- [X] Python SDK
- [X] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 0.2.1

### Describe the problem

When logging to Opik using the evaluate function, I get the following error: 

`OPIK: You are attempting to log data into a nested span under the project name "ppl_test". However, the project name "None" from parent span will be used instead.`

My experiment data then logs to the correct Experiment in the Opik UI, but will only log to the `Default Projects` project. 

### Reproduction steps

I am setting my configuration parameters as follows:

```
import opik

os.environ["OPIK_API_KEY"] = userdata.get('XXX')
os.environ["OPIK_WORKSPACE"] = "XXX"
OPIK_PROJECT_NAME = "XXX"

opik.configure()
```

and then setting the project name within the track decorator:

```
@track(project_name = OPIK_PROJECT_NAME)
```

**Update:** I believe the issue originates with setting the `project_name` within the `@track` decorator on the inner functions called within the `evaluate` function. It looks like `opik.evaluation.evaluate` pulls the `project_name` from `experiment_config`, which defaults to `None`, so the inner function calls attempt to create nested spans with a project of a new name.

**Comment by jverre** [comment]
Thanks for the report @anmorgan24. We have been able to reproduce the issue and will fix it in an upcoming version

**Comment by anmorgan24** [comment]
Thanks!

**Comment by chasefortier** [comment]
I am facing the same issue- great to hear a fix is already in progress. I wanted to add that I am also getting the error when additionally passing project_name into the track_openai method:

`track_openai(openai.Client(), project_name = PROJECT_NAME)`

in addition to the track decorator:

`@track(project_name=PROJECT_NAME)`

**Comment by jverre** [comment]
This has been resolved, you just need to update the Python SDK to not have this issue anymore
