### ISSUE TITLE
[Bug]: Async Task Span Tracking Error: Missing Spans in Concurrent Processing

### ISSUE THREAD

**Issue by Jeff-67** [comet-ml/opik#424]
### Willingness to contribute

No. I can't contribute a fix for this bug at this time.

### What component(s) are affected?

- [X] Python SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 0.1.23

### Describe the problem

When using the `evaluate_reference_factual_correctness` function, span tracking intermittently fails when processing multiple tasks using `asyncio.gather`. Approximately 2-3 out of 10 tasks fail to track the span.

Relevant logs:

```
OPIK: Failed to process AddSpanFeedbackScoresBatchMessage. Content: AddSpanFeedbackScoresBatchMessage(batch=[FeedbackScoreMessage(id='06711f79-bc31-779b-8000-fb1135bf3f3a', project_name='Default Project', name='factual_correctness', value=0.33)]), Error: status_code: 409, body: {'errors': ['project_name from score and project_id from span does not match']}
```

Additionally, there's a rare occurrence of a 500 error:

```
OPIK: Failed to process AddSpanFeedbackScoresBatchMessage. Error: status_code: 500, body: {'code': 500, 'message': 'There was an error processing your request. It has been logged (ID 4aa0090b75ded0ec).'}
```

The issue seems to be related to race conditions during concurrent tasks execution.

### Reproduction steps

1. Set the environment configuration like this:

```python
import opik
openai_client = track_openai(openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY")))
ragas_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini"))
factual_correctness_metric = FactualCorrectness(llm=ragas_llm, mode = "precision")
opik.configure(use_local=True)
```

2. Use the following code within the track decorator:

```python
@track(name="Compute Ragas")
async def compute_factual_correctness_score(factual_correctness_metric, answer, contexts, project_name) -> float:
    score = await compute_metric(factual_correctness_metric, {"response": answer, "reference": contexts}, project_name)
    update_current_span(feedback_scores=[{"name": "factual_correctness", "value": score}])
    return score

@track(project_name='test_evaluation', name='Evaluate content faithfulness')
async def evaluate_reference_factual_correctness(report: str):
    try:
        async def process_data(data):
            return await compute_factual_correctness_score(factual_correctness_metric, data['content'], data['ref'], "test_evaluation")

        scores = await asyncio.gather(*[process_data(data) for data in content_and_reference])
        total_score = sum(scores)
        average_score = total_score / len(content_and_reference)

        update_current_trace(feedback_scores=[{"name": "factual_correctness", "value": average_score}])
```

3. Run the function with multiple tasks using `asyncio.gather` and observe intermittent span tracking failures.

**Comment by jverre** [comment]
Thanks for the report @Jeff-67 

We have fixed the 500 error as part of the [PR](https://github.com/comet-ml/opik/pull/395), it should be released to Opik Hosted in the next few days.

@alexkuzmik Can you take a look at the issue with `project_name from score and project_id from span does not match`

**Comment by alexkuzmik** [comment]
Hi @Jeff-67!
Thanks for reporting. The changes that should fix `project_name` issue have just been merged to `main` and released to pypi.

**Comment by Jeff-67** [comment]
huge thanks to @alexkuzmik  and @jverre. It works well now!
