### ISSUE TITLE
[FR]: Context-less Hallucination Metric

### ISSUE THREAD

**Issue by caleb-kaiser** [comet-ml/opik#430]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal summary

It would be nice to optionally specify whether the Hallucination() metric should evaluate a context-question-answer triplet, or just an input-output pair. 

### Motivation

The current Hallucination() metric is based on a prompt which directs the critic model to assess the relationship between information in the output and information in the context. For tasks that do not use additional context beyond the input, this is problematic, as the critic model can incorrectly flag outputs as hallucinations due to the empty context field.

**Comment by jverre** [comment]
This is a good idea, we are taking a look at how to implement this

**Comment by jverre** [comment]
This has been merged and will be released soon
