### ISSUE TITLE
[Bug]: Unable to delete dataset item in the UI

### ISSUE THREAD

**Issue by jverre** [comet-ml/opik#472]
### Willingness to contribute

No. I can't contribute a fix for this bug at this time.

### What component(s) are affected?

- [ ] Python SDK
- [ ] Opik UI
- [X] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.0.1-290

### Describe the problem

Unable to delete a dataset item from the UI, the request hangs for a little while before returning a 500 error

### Reproduction steps

To reproduce:
1. Navigate to dataset page
2. Click on dataset
3. Click on the three dots at the end of a dataset item row
4. Click on delete

After around 20 seconds, a 500 error is returned from the backend

**Comment by thiagohora** [comment]
I wasn't able to reproduce this issue. Looking at the logs, it seems like a temporary issue during migration execution. Feel free to re-open if the error persists, but it's back to normal now.
