### ISSUE TITLE
[FR]: Add multi-select options for Dataset view

### ISSUE THREAD

**Issue by gidim** [comet-ml/opik#494]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

It would be great if the experiment/dataset/projets pages UI is consistent. At the moment you can only delete one dataset at the time.

### Motivation

I have created 13 datasets which i don't want to keep. It's annoying to manually delete each

**Comment by jverre** [comment]
@idoberko2 Can you take a look at this, I think we might have an endpoint missing for deleting multiple datasets

**Comment by idoberko2** [comment]
@jverre from what I see all resources lack multiple deletion endpoints

**Comment by SrBliss** [comment]
In addition to deleting multiple datasets it would be useful to be able to delete multiple DatasetItems within a Dataset
