### ISSUE TITLE
[FR]: Render images for Datasets containing image URLs

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#496]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

As Opik supports Multimodal Traces, where images will automatically be detected and rendered in the Opik UI, for image-based use cases it would be nice to have images detected/rendered also in Datasets containing image URLs.

### Motivation

I am working on a use case where information is extracted from images. I am testing different custom metrics for this task and curating several Datasets that I want to use for the Experiments. Visually identifying the images in the UI is much easier than just looking at the URLs.

**Comment by jverre** [comment]
This is now released
