### ISSUE TITLE
[FR]: Add Visualizations to Project View

### ISSUE THREAD

**Issue by chasefortier** [comet-ml/opik#519]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

It would be useful to see average metrics over time for the traces logged to the project tab. 

### Motivation

For traces being logged from production, I want to see how daily performance is changing day to day in order to act quickly on any degradation. 

During development, I want to see if the application's performance is improving as I continue to make enhancements.

**Comment by jverre** [comment]
Hi @chasefortier 

This is something we have been looking and we agree it would be super useful! 

We will be shipping this in a couple weeks:
![image](https://github.com/user-attachments/assets/bd123179-8fbf-4460-bef5-f5fe03cd30af)

We will post updates on this thread

**Comment by jverre** [comment]
This has now been released
