### ISSUE TITLE
[Bug]: Evaluation saves traces to Default Project despite having set the OPIK_PROJECT_NAME env variable

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#524]
### Willingness to contribute

No. I can't contribute a fix for this bug at this time.

### What component(s) are affected?

- [X] Python SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.0.3

### Describe the problem

Traces generated when calling the evaluate method are saved to the Default Project despite having set the OPIK_PROJECT_NAME environment variable

### Reproduction steps

Code and output:

```
SWEEP_ID = "06"

# Project to track evaluation traces
os.environ["OPIK_PROJECT_NAME"] = f"{PROJECT_NAME}-{SWEEP_ID}"

for i, prompt in enumerate(system_prompts):
    SYSTEM_PROMPT = prompt
    experiment_config = {"system_prompt": SYSTEM_PROMPT, "model": "gpt-3.5-turbo"}
    experiment_name = f"comet-chatbot-{SWEEP_ID}-{i}"

    res = evaluate(
        experiment_name=experiment_name,
        dataset=dataset,
        experiment_config=experiment_config,
        task=evaluation_task,
        scoring_metrics=[hallucination_metric,
                         answerrelevance_metric]
    )

Evaluation:   0%|          | 0/5 [00:00<?, ?it/s]OPIK: Started logging traces to the "Default Project" project at https://www.comet.com/opik/rodrigom-comet/projects/.
```

**Comment by jverre** [comment]
Thanks @SrBliss, indeed it should work as you described. We'll look into it

**Comment by jverre** [comment]
The project name can be configured for the `evaluate` function using the `project_name` parameter, closing this one for now

**Comment by jverre** [comment]
The project name can be configured for the evaluate function using the project_name parameter, closing this one for now
