### ISSUE TITLE
[FR]: Wrap text on Dataset table

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#526]
### Willingness to contribute

No. I can't contribute this feature at this time.

### Proposal summary

When changing the cell height, text is not wrapped so the additional space is not actually used. See images.
![image](https://github.com/user-attachments/assets/4694a9d6-c55e-4e79-a0d9-b88075b5499b)
![image](https://github.com/user-attachments/assets/4d7a4f75-830c-411f-9292-d6955d534537)

### Motivation

It would be useful to view as much content as possible in the table, without needing to click on each row.

**Comment by SrBliss** [comment]
I just noticed that in the Experiments table, content of the "input" and "output" columns is also not wrapped.

![image](https://github.com/user-attachments/assets/0d58ceb0-c7da-4a7f-afc5-48681980cb0c)

**Comment by jverre** [comment]
We are planning quite a few different improvements in how the data is displayed in all table so that we display more data, this will be released next week
