### ISSUE TITLE
[FR]: Search and export span

### ISSUE THREAD

**Issue by NaniNorris** [comet-ml/opik#537]
### Proposal summary

Issue Description:

In the Opik SDK, users currently have the capability to search for traces by project name. However, there is no similar functionality available for searching spans. Presently, users can retrieve span content by providing the span ID. This process requires users to manually navigate the UI to obtain the span ID before performing the search.

Proposed Enhancement:

To improve efficiency and streamline the workflow, it is proposed to implement a feature that allows users to search spans by Trace ID. This enhancement would facilitate easier and quicker access to both trace and span data, enabling users to export this information for further analysis without the need for manual intervention to retrieve span IDs.

### Motivation

Current in advance RAG unable to log the token consumptions in trace. It is logged in the intermediate spans. So for analysis we to the get the spans.

**Comment by jverre** [comment]
Hi @NaniNorris 
This makes sense, are you looking for a function similar to [`search_traces`](https://www.comet.com/docs/opik/tracing/export_traces#search-for-specific-traces) but that returns spans ?

We have a [REST API method](https://www.comet.com/docs/opik/reference/rest_api/get-spans-by-project) so should be able to add one easily in the SDK

**Comment by NaniNorris** [comment]
Thank you for the support. The REST API methos is useful. 

Exited to see the feature coming to SDK.

**Comment by jverre** [comment]
Code was merged, will be released tomorrow in a new SDK release

**Comment by jverre** [comment]
@NaniNorris This has now been released, you will need to update the Python SDK version and docs for the new method are here: https://www.comet.com/docs/opik/tracing/export_data#exporting-spans

If there is anything else we can help with, just let me know !
