### ISSUE TITLE
[FR]: Add "not-equal" operator for Filtering

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#551]
### Proposal summary

Today "not-equal" is not an option when Filtering traces on a Project table.
![image](https://github.com/user-attachments/assets/9cb67181-a278-4c71-9567-564fea645739)

### Motivation

Although there can be workarounds depending on the scenario, sometimes the best filter to find low performing traces is "not a specific value".

**Comment by jverre** [comment]
Good idea, this is not supported yet but we will take a look
