### ISSUE TITLE
[Bug]: Cannot filter traces on Feedback scores when the source is "SDK"

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#553]
### What component(s) are affected?

- [ ] Python SDK
- [X] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.0.4

### Describe the problem

Filters for a Feedback score when the source = 'SDK' return no results. Filters for feedback scores when they are manual annotations do work (source = 'ui')
![image](https://github.com/user-attachments/assets/5c1d4bd9-93a9-4503-bf22-512ff5d31f8f)
![image](https://github.com/user-attachments/assets/e71be8d4-97eb-4f99-a314-da1d07818516)

### Reproduction steps

Create a feedback score manually, from the UI, using the Annotate button. This will be `source = 'ui'`

Create a feedback score using the SDK, with a code similar like the one below. This will be `source = 'SDK'`

```
def evaluation_task(x):
    full_response = rag_bot.get_answer(x['input'], SYSTEM_PROMPT)
    response = full_response["response"]
    context = full_response["context"]
    return {
        "input": x['input'],
        "output": response,
        "context": full_response["context"]
    }

hallucination_metric = Hallucination(name="Hallucination")
answerrelevance_metric = AnswerRelevance(name="AnswerRelevance")

SWEEP_ID = "11"

for i, prompt in enumerate(system_prompts):
    SYSTEM_PROMPT = prompt
    experiment_config = {"system_prompt": SYSTEM_PROMPT, "model": "gpt-3.5-turbo"}
    experiment_name = f"comet-chatbot-{SWEEP_ID}-{i}"

    res = evaluate(
        dataset=dataset,
        experiment_name=experiment_name,
        experiment_config=experiment_config,
        project_name=f"{PROJECT_NAME}-{SWEEP_ID}",
        task=evaluation_task,
        scoring_metrics=[hallucination_metric,
                         answerrelevance_metric]
    )
```

**Comment by SrBliss** [comment]
Example screenshot for `source='sdk'` feedback scores.
![image](https://github.com/user-attachments/assets/1fc79a1a-429f-4850-ad2c-431e77cbd4cd)

**Comment by jverre** [comment]
@ferc Can you take a look at this one tomorrow

**Comment by ferc** [comment]
@SrBliss thanks for raising, I just confirmed that giving a custom `project_name` to the `evaluate` function causes the issue (the feedback scores are not linked to the correct project), we'll fix it soon and I'll update the status here

Again, thanks for reporting it!
