### ISSUE TITLE
[FR]: Allow sorting tables by columns

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#560]
### Proposal summary

Allow sorting tables by any column: Projects, Datasets, Experiments and Feedback definitions

### Motivation

To work with a significant amount of experiments/projects I need to be able to quickly sort by "Last Update" or "Name" for example.

**Comment by jverre** [comment]
We are currently working on adding sorting for project tables, should be ready in the next few days. We will then work on the other tables

**Comment by jverre** [comment]
Sorting has been released for the project table 🚀 Marking as done
