### ISSUE TITLE
[FR]: Looking for certificate of course completion. 

### ISSUE THREAD

**Issue by hrithiksagar** [comet-ml/opik#594]
### Proposal summary

I have completed the course "https://www.comet.com/site/llm-course/," but I am unable to find a certificate of completion or participation so that I can add this to LinkedIn. Is this feature there, and I missed it, or are you planning on adding this?

**Comment by jverre** [comment]
Hi @hrithiksagar
We are not currently offering a certificate of completion for the course but we will take your suggestion onboard !
