### ISSUE TITLE
[Bug]: levenshtein version incompatibility

### ISSUE THREAD

**Issue by oegeshipster** [comet-ml/opik#598]
### What component(s) are affected?

- [X] Python SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.1

### Describe the problem

seems there is an issue with the depencencies:

```sh
uv add opik==1.1
  × No solution found when resolving dependencies for split (python_full_version == '3.11.*'):
  ╰─▶ Because opik==1.1.0 depends on levenshtein>=0.25.1,<0.26.dev0 and python-levenshtein==0.26.1 depends on levenshtein==0.26.1, we can conclude that opik==1.1.0 and python-levenshtein==0.26.1 are incompatible.
      And because only python-levenshtein<=0.26.1 is available, we can conclude that opik==1.1.0 and python-levenshtein>=0.26.1 are incompatible.
      And because your project depends on opik==1.1 and python-levenshtein>=0.26.1, we can conclude that your project's requirements are unsatisfiable.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.
```

when simply running `uv add opik` it installs version 0.1 due to this incompatibility.  With pip install it tries to build the wheel for the levenshtein package and also fails in my case:

```sh
Building wheels for collected packages: levenshtein
  Building wheel for levenshtein (pyproject.toml) ... error
  error: subprocess-exited-with-error
```
should be something that you should be able to catch in CI before release?

**Comment by dsblank** [comment]
@oegeshipster, thanks for reporting the issue!

@andrescrz, I see that we have levenshtein pinned to "~=0.25.1" here: https://github.com/comet-ml/opik/blame/main/sdks/python/setup.py#L41

Do you know if there is a reason we selected that version?

**Comment by oegeshipster** [comment]
realized that the uv  incompatibility was due to my dependencies for `thefuzz` package. Closing this, although in general it would be good not to have too many upper limits on versions, as you will run into these issues. (as a oss library maintainer myself I know the pain :)

**Comment by andrescrz** [comment]
> @oegeshipster, thanks for reporting the issue!
> 
> @andrescrz, I see that we have levenshtein pinned to "~=0.25.1" here: https://github.com/comet-ml/opik/blame/main/sdks/python/setup.py#L41
> 
> Do you know if there is a reason we selected that version?

@alexkuzmik @japdubengsub can you give more context here?

**Comment by dsblank** [comment]
@oegeshipster thanks for the additional feedback. Agreed that it is a hard decision to make on pinned upper limits :+1:

**Comment by ldaugusto** [comment]
I had the same problem installing via pip as @oegeshipster mentioned.

I was using Python 3.13, but lowering to 3.12 worked just fine.
