### ISSUE TITLE
[FR]: handle (large) base64 encoded images

### ISSUE THREAD

**Issue by oegeshipster** [comet-ml/opik#605]
### Proposal summary

opik should support base64 images, not just urls, even when the images are large-ish.

### Motivation

for our usecase we are uploading multipage pdfs as one base64 encoded image each to openai for structured output extraction.  This works fine with langsmith that happily processes and displays the image on the platform. However with opik I get an `**413 Request Entity Too Large**` error in `_process_create_span_batch_message`. 

with base64 encoded images size can get quite substantial!

**Comment by dsblank** [comment]
@oegeshipster I believe we have a fix for this that almost finished.

**Comment by ferc** [comment]
@oegeshipster thanks for raising this ticket! in order to understand better your use case, could you clarify a bit the amount base64 images per span, the amount of spans and the approximately size of those images that you're trying to log?

Thank you very much for your feedback!

**Comment by jverre** [comment]
Hi @oegeshipster 
We've improved the batching mechanism in the SDK to avoid these issues: https://github.com/comet-ml/opik/pull/648. You can now log traces that are up to 50MB without facing the `**413 Request Entity Too Large**` error.

Will be released as part of the next SDK release today or tomorrow
