### ISSUE TITLE
[FR]: Make pandas, numpy an optional dependency for the Python SDK

### ISSUE THREAD

**Issue by SanjayBysani** [comet-ml/opik#644]
### Proposal summary

We are using Opik from within AWS Lambda, and numpy impacts the package size significantly. Unfortunately, it's required as a top-level import, and we use the SDK for only tracing purposes. Can we update the SDK to support working without a numpy dependency ?

**Comment by alexkuzmik** [comment]
Hi @SanjayBysani!
That's a good suggestion. Yes, we'll exclude pandas from the dependencies (probably next week).

**Comment by SanjayBysani** [comment]
Thanks @alexkuzmik

**Comment by AjdinBajric** [comment]
@aadereiko, @alexkuzmik thank you so much for the quick turnaround! Would it be possible to release this soon?

**Comment by alexkuzmik** [comment]
@AjdinBajric it's released :)
