### ISSUE TITLE
[FR]: Display User Names Across Projects, Datasets, and Experiments for Improved Collaboration Tracking

### ISSUE THREAD

**Issue by harishtr11** [comet-ml/opik#649]
### Proposal summary

The current system does not display user names in the Projects table, Datasets, and Experiments views, which hampers the ability to identify who made specific contributions or logged changes during collaborative efforts. To enhance accountability and streamline communication among team members, it is crucial to implement a feature that shows user names alongside their entries in all relevant sections. This improvement will facilitate better tracking of contributions across projects, datasets, and experiments, promoting a more collaborative and transparent working environment for all users.

**Comment by jverre** [comment]
Hi @harishtr11 
I took a look and can see from the [Rest API docs](https://www.comet.com/docs/opik/reference/rest_api/opik-rest-api) that we actually return this field already for most objects, we'll add it in the UI
