### ISSUE TITLE
How to changing the LLM on the evaluations that don't support litellm yet, but have an OpenAI-compatible endpoints. 

### ISSUE THREAD

**Issue by carlesoctav** [comet-ml/opik#663]
How can I do that? The inference engine I use supports an OpenAI-like endpoints, but in litellm itself, it currently only supports the embedding model.

**Comment by jverre** [comment]
Hi @carlesoctav 
Can you share more about the OpenAI proxy ? I thought LiteLLM supported OpenAI-compatible endpoints already: https://docs.litellm.ai/docs/providers/openai_compatible

**Comment by carlesoctav** [comment]
Yes, it supports that. The problem I’m facing is that I cannot pass the base_url because it’s prohibited by the LiteLLMChatModel class. I’ve manually edited each completions function to use a specific base_url, and it works well (though there’s another error because the engine doesn’t support structured output yet). Because of these, I try to figure out how to change the base_url without directly modifying the completions function.

**Comment by carlesoctav** [comment]
on the other side, i've found a solution by creating SomeModel class based on base_model.OpikBaseModel, and pass it on the metrics class, and i'm happy with this.

**Comment by demdecuong** [comment]
@carlesoctav hi brother, can you give me example code from your solution. It seems like i have similar problem to you.
You mean something like this right ?

```
class WrapperModelUrl(base_model.OpikBaseModel):
    pass

class Hallucination(base_metric.BaseMetric):
    def __init__(
        self,
        model: Optional[Union[str, WrapperModelUrl]] = None,
        name: str = "hallucination_metric"
)
```

**Comment by carlesoctav** [comment]
Yes, you dont need to modify the metric input tho. Just past the model in the metrics.

```python
llm_judge = WrapperModel()
metrics = Hallucination(model =llm_judge)

```
The code for the wrapper mainly the same thing for LiteLLMChatModel, but with an openai client instead of litellm (check the self._engine) with a spesific baseurl.

**Comment by carlesoctav** [comment]
For the structured output problem, you need    to check how ur engine can handle it.

For my case, since i use vllm, i can simulate this feature.
https://docs.vllm.ai/en/latest/models/structured_outputs.html

**Comment by alexkuzmik** [comment]
Hi @carlesoctav @demdecuong!
Regarding the passing of arguments to completions rather than just a model name.
I'd like to add that you can create an instance of LiteLLMChatModel yourself just like you did with the custom OpikBaseModel subclass.
Any arguments that you want to pass to the completion calls can be passed to the `LiteLLMChatModel.__init__` function.
```python
model = LiteLLMChatModel(name="some-model-name", base_url="some-url")
hallucination = Hallucination(model=model)
```
We will probably highlight it in the docs and explicitly move to public API

**Comment by jverre** [comment]
I've also updated the docs page to make it easier for new users to use custom models: http://localhost:3000/docs/opik/evaluation/metrics/custom_model
