### ISSUE TITLE
[FR]: Add a "last updated" column in the projects view as default

### ISSUE THREAD

**Issue by gidim** [comet-ml/opik#673]
### Proposal summary

Currently the projects view shows the name and the created date/time of the project. Would be helpful to add "Last Updated" as a default

**Comment by ferc** [comment]
@gidim indeed that's a very valid point and it's the case for new users in the platform, for old users unfortunately unless you clear the browser cache you'll see your old settings of the table (without the `Last updated` column)

For your user you can add the column in the UI manually (clicking into the `Columns` button) but for new users it's the new default to display it and to make the project table sorted descendant by that column (displaying the projects with recent activity first)

We'll consider this kind of settings migrations for future changes, thanks for your feedback, in case you want to try the default configuration you can clear the browser data of the site checking the option `Cookies and other site data`

Let me know if the answer helped, if that's the case then we can close the issue, thanks again

**Comment by jverre** [comment]
Since this is supported for new users, closing this for now
