### ISSUE TITLE
[Bug]: Incorrect "Most recent experiment" date in Datasets table

### ISSUE THREAD

**Issue by SrBliss** [comet-ml/opik#676]
### What component(s) are affected?

- [ ] Python SDK
- [X] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.1.8

### Describe the problem

"Most recent experiment" date in Datasets table is not correct.

- I have an example where that date shows today, but when going to Experiments there is no Experiment executed today.
- I have another example where the dataset shows the date of today and there are no Experiments with that dataset: Dataset `Comet_Question_1` in the screenshots.

![image](https://github.com/user-attachments/assets/54f2c837-ef7f-4473-8a59-f8672d78e38c)
![image](https://github.com/user-attachments/assets/58050f16-5612-4741-8ef0-19e68ba3375b)

**Comment by jverre** [comment]
We are working on a fix for this
