### ISSUE TITLE
[Bug]: Metric Score Rendering in Experiments UI

### ISSUE THREAD

**Issue by sherpan** [comet-ml/opik#705]
### What component(s) are affected?

- [ ] Python SDK
- [X] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.1.9

### Describe the problem

The eval metrics are barely legible in this Experiments UI 

![Screenshot 2024-11-22 at 11 22 13 AM](https://github.com/user-attachments/assets/7c585daf-a9d1-4aac-bf4b-ba6b82185c98)

**Comment by jverre** [comment]
We are updating this table to display each score in a separate column (see linked design) that should solve this issue:
![Experiments - Feedback scores as columns](https://github.com/user-attachments/assets/ee4fb909-8d08-4de0-87ae-4520ed775f3c)

**Comment by ferc** [comment]
The change described by @jverre has been solved in the `1.1.11` version, thanks for sharing your feedback! :)
