### ISSUE TITLE
[FR]: Return projectID and traceID

### ISSUE THREAD

**Issue by NaniNorris** [comet-ml/opik#835]
### Proposal summary

HI Team,

While using the langchain callbacks integration and trace the logs, it will be very helpful to return the trace id and project id for that particular trace which can be logged against datapoint in a seperate dataframe with some additional custom log details. It will be very helpful later to identify the trace and fetch from the opik client api based on the IDs.

### Motivation

It will solve the filter mechanism to identify the exact trace based on the user custom information

**Comment by jverre** [comment]
@NaniNorris have you seen this part of the docs: https://www.comet.com/docs/opik/tracing/integrations/langchain#accessing-logged-traces, should allow you to get the TraceID for logged traces. Is this what you are looking for ?

**Comment by NaniNorris** [comment]
Hi @jverre, Thank you sharing document, Yes this is what I am looking for thank you
