### ISSUE TITLE
Discussion links return 404

### ISSUE THREAD

**Issue by tkakantousis** [comet-ml/opik#836]
Links in below doc snippet return 404

https://github.com/comet-ml/opik/blob/f263d2e0482882f37d47b8618e3887cd5d9a2eae/apps/opik-documentation/documentation/docs/roadmap.md?plain=1#L50-L55

**Comment by jverre** [comment]
Thanks for the report @tkakantousis, we moved away from discussions to GitHub issues. I'll update the link tomorrow

**Comment by jverre** [comment]
Docs have been updated

**Comment by tkakantousis** [comment]
Great, thank you for the quick turnaround
