### ISSUE TITLE
[FR]: Get evaluation outputs. No client.get_experiment 

### ISSUE THREAD

**Issue by StoyanStAtanasov** [comet-ml/opik#851]
### Proposal summary

Add a get_experiment so the experiment data could be used externally like there is get_dataset

### Motivation

After an evaluation that shows that the output is good, there is no (obvious) way get the information back for further use.
There is a way to create a dataset, but no way to get outputs of the dataset back. At least I could not find them in the client = Opik()

**Comment by jverre** [comment]
@StoyanStAtanasov Good idea, we can add it in the next couple of days.

To make sure we provide the right data back, what are you expecting in terms of data:
1. Evaluation task inputs (ie. dataset item data)
2. Evaluation outputs (ie. outputs)
3. Evaluation scores (ie. scores for each output)

Anything else you would need ?

**Comment by StoyanStAtanasov** [comment]
Hey @jverre, thank you for the fast reply! Yes, basically the results of my llm processing are in the outputs, but the evalutaions are important to selectively use the outputs.

**Comment by StoyanStAtanasov** [comment]
@jverre  Judjing by your response you may be interested in feedback, I have used your system in the past week to apply llms to real industrial data problems. I have a bunch of issues I had to work around. What would be the best way, is it a bunch of FRs or another way?

**Comment by jverre** [comment]
@StoyanStAtanasov Indeed we love feedback !

The best approach is to create FR requests, it helps other users see the issues we are currently working on and track when they are resolved

**Comment by jverre** [comment]
This has now been released and documented here: [https://www.comet.com/docs/opik/evaluation/evaluate_your_llm#accessing-logged-experiments](https://www.comet.com/docs/opik/evaluation/evaluate_your_llm#accessing-logged-experiments)

**Comment by jverre** [comment]
This has now been released and documented here: https://www.comet.com/docs/opik/evaluation/evaluate_your_llm#accessing-logged-experiments
