### ISSUE TITLE
[FR]: Consistent Experiments Dataset focus after page refresh or add refresh button (30s autorefresh is too long)

### ISSUE THREAD

**Issue by StoyanStAtanasov** [comet-ml/opik#861]
### Proposal summary

Make the Experiments page ( http://localhost:5173/default/experiments) consistent with selected dataset after refresh.
Or
Add a refresh button to refresh the experiments for the selected dataset.

### Motivation

As the experiments are run externally, after a refresh to see the new experiment results, the experiments page loses it's dataset selection and shows you again all datasets, which prevents you from focusing on the dataset you are working on.
Or
Add refresh button to directly get the new experiment data.

**Comment by jverre** [comment]
Good suggestion, I think we can improve the search functionality in that page as well

@olesya-comet Can you take a look next week ?

**Comment by jverre** [comment]
Hi @StoyanStAtanasov 
This has been selected for development this week, will keep you posted on progress

**Comment by StoyanStAtanasov** [comment]
[like]  Stoyan Atanasov reacted to your message:
________________________________

**Comment by jverre** [comment]
We have released a number of improvements for this, you can see exactly what is saved in the linked PR
