### ISSUE TITLE
[FR]: add output formats as it own fields for prompts

### ISSUE THREAD

**Issue by neotea** [comet-ml/opik#866]
### Proposal summary

In my prompts I often define the output format as json. i would like to keep track of this and split this from the prompt itself in the UI.

### Motivation

The feature would organize the prompt versioning better especially in the cases where the output must be a predefined json.

**Comment by jverre** [comment]
Hi @neotea 
We are planning some improvements with prompts so we support two different types of prompts:
1. Text prompts: This is what we have today
2. Chat prompts: Instead of just being text, would include `messages`, `model parameters` and `response_format`

This might take a couple of weeks but definitely something that is top of mind !

**Comment by neotea** [comment]
Awesome. Currently I have a lot of "summarize texts to specific json format and then output to html" tasks. At openAI i can specify structured json format as output: https://platform.openai.com/docs/guides/structured-outputs#json-mode
Therefore I am looking for a solution to enhance the prompts while staying with the output format. Currently in development mode I also have to change the json sometimes, thats why i don't want to hardcode it. But for butter organization I also don't want to have it in the prompt all the time. 
Is there in the improvements also planned to differentiate between system and user messages? 

Also for structured output it would perfect if the platform would offer a  templates section for responses (but thats probably another feature idea...).

looking forward to your roadmap!

**Comment by jverre** [comment]
Hi @neotea 
This has been selected for development this week !

We will make a first improvement this week by adding an optional `metadata` field to prompts, that way you can save the structured output separately from the prompt text.

Then as a separate improvements we will introduce the chat prompts that allow you to save both system and user messages in the same prompt. This will take a bit longer but in the short term roadmap as it overlaps with the Playground feature we are working on
