### ISSUE TITLE
Opik stack and databases

### ISSUE THREAD

**Issue by harinisri2001** [comet-ml/opik#960]
@Nimrod007 @jverre  Hi I would like to know the architecture of Opik. What is the purpose of all three databases in the stack?
What is the purpose of MySQL, Redis, and ClickHouse? Also what other alternates are there for these three? Or only these three are supported?
All three are mandatory for Opik to be up and running?

**Comment by Nimrod007** [comment]
Hi @harinisri2001,

You're absolutely correct—Opik utilizes multiple databases for different purposes:

* ClickHouse: Serves as the primary database for storing most of the data, including traces, datasets, and experiments.
* MySQL: Handles relational data such as project information and user metadata.
* Redis: Manages short-lived data for tasks like event deduplication and distributed locks.

All of them are mandatory to run Opik.

From a user's perspective, this setup is entirely managed through Docker Compose (for local environments), Helm (for production deployments), or seamlessly abstracted when using Comet.com (completely free).

Let us know if you have any further questions!

**Comment by Nimrod007** [comment]
@harinisri2001 closing this, feel free to open if you have further questions, in addition you can chat directly on chat.comet.com if you have specific (non public) questions. 

Thanks!

**Comment by harinisri2001** [comment]
> Hi @harinisri2001,
> 
> You're absolutely correct—Opik utilizes multiple databases for different purposes:
> 
> * ClickHouse: Serves as the primary database for storing most of the data, including traces, datasets, and experiments.
> * MySQL: Handles relational data such as project information and user metadata.
> * Redis: Manages short-lived data for tasks like event deduplication and distributed locks.
> 
> All of them are mandatory to run Opik.
> 
> From a user's perspective, this setup is entirely managed through Docker Compose (for local environments), Helm (for production deployments), or seamlessly abstracted when using Comet.com (completely free).
> 
> Let us know if you have any further questions!

@Nimrod007 Thank You so much. One small confirmation, Is it possible to setup alternate databases? Or only these three are supported?
